UI/Areas/Admin/Controllers/CustomPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Helpers;
using Core.Models;

namespace Core.Areas.Admin.Controllers
{
    [AuthorizationFilter(Security.Role.Super_Administrator)]
    public class CustomPageController : Controller
    {

        private DB.Context db;
        private IRepository<CustomPage> repo;

        public CustomPageController()
        {
            this.db = new DB.Context();
            this.repo = new DB.Repository<CustomPage>(this.db);
        }

        public ActionResult Index(int pageId)
        {
            ViewData["PageId"] = pageId;

            CustomPage customPage = repo.Retrieve(x => x.PageId == pageId, null, null).SingleOrDefault();
            if (customPage != null)
            {
                //edit
                return View(customPage);
            }
            else
            {
                //add
                return View(new CustomPage());
            }
        }

        [HttpPost]
        public ActionResult Index(int pageId, FormCollection form)
        {
            ViewData["PageId"] = pageId;
            Page p = db.Set<Page>().Find(pageId);
            CustomPage customPage = repo.Retrieve(x => x.PageId == pageId, null, null).SingleOrDefault();
            if (customPage != null)
            {
                //update
                TryUpdateModel(customPage);
                if (ModelState.IsValid)
                {
                    repo.Update(customPage);
                }
            }
            else
            {
                //insert
                CustomPage cp = new Models.CustomPage();
                cp.Page = p;
                cp.Controller = form["Controller"].ToString();
                cp.Action = form["Action"].ToString();

                if (ModelState.IsValid)
                {
                    repo.Add(cp);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    repo.Save();
                    return RedirectToAction("Index", "Page");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    Error.Exception(ex, "/CustomPage/Index");
                }
            }

            return View(customPage);
        }

    }
}

UI/Areas/Admin/Views/CustomPage/Index.cshtml
@model CustomPage
@{
    ViewBag.Title = "Body";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageId = 0;
    if(ViewData["PageId"] != null)
    {
        pageId = Convert.ToInt32(ViewData["PageId"]);
    }
    
}

<div class="actionBox">
    <h2>Custom Page</h2>
    <div class="actionContent">
    <h3>Page: </h3>
        <p class="headerOptions">
             @Html.ActionLink("<< Pages", "Index", new{controller = "Page", action = "Index"})        
        </p>
        @if(!ViewData.ModelState.IsValid)
        {
            <p class="error">@Html.ValidationSummary(true)</p>
        }
        
        @using (Html.BeginForm("Index", "CustomPage", new { controller = "CustomPage", action = "Index", pageId = @pageId }, FormMethod.Post))
        {            
            @Html.Hidden("pageId", pageId);
                                          
            <h4>Controller:</h4>
            @Html.TextBoxFor(m=>m.Controller)
            <span class="error">@Html.ValidationMessageFor(m=>m.Controller)</span>
            
            <h4>Action:</h4>
            @Html.TextBoxFor(m=>m.Action)
            <span class="error">@Html.ValidationMessageFor(m=>m.Action)</span>
            
            <div class="buttonContainer">
                <input type="submit" value="Save" class="button" />
                <input type="button" value="Cancel" class="button" onclick="window.location='@Url.Action("Index", "Page", new { controller = "Page" })';" />
            </div>
        }
      
     </div>
</div>
@section HeadScripts
{    
    
}